name: Docker Builds

on: [push]

jobs:
  build:
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v3
      - name: docker build
        run: |
          docker build . -t personal-site
      - name: docker run
        run: |
          if [ $( docker ps -a | grep personal-site | wc -l ) -gt 0 ]; then
            docker stop personal-site
            docker remove personal-site
          fi
          docker run -p=3000:3000 --restart=always personal-site
    
